accounts/urls.py
from django.urls import path
from . import views as account_views


app_name = 'accounts'

urlpatterns = [
    path('signup/', account_views.signup, name='signup'),
    ]

blog/urls.py
from django.urls import path
from .views import HomePageView, DetailDishView, CreateDishView, UpdateDishView, DeleteDishView
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('<int:pk>/', DetailDishView.as_view(), name='detail'),
    path('create/', staff_member_required(CreateDishView.as_view()), name='dish-create'),
    path('update/<int:pk>/', staff_member_required(UpdateDishView.as_view()), name='dish-update'),
    path('delete/<int:pk>/', staff_member_required(DeleteDishView.as_view()), name='dish-delete'),
]

widelcem/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('register/', auth_views.logout, name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Dish(models.Model):
    name = models.CharField(max_length=128)
    portions = models.IntegerField(default=2, null=True, blank=True)
    ingredients = models.TextField(default="", null=True, blank=True)
    description = models.TextField(default="", null=True, blank=True)
    added = models.DateField(null=False, blank=True, default=timezone.now)   # blank działa na rekordy w db
    photo0 = models.ImageField(upload_to='images/', null=False, blank=True, default='images/000empty.jpg')
    photo1 = models.ImageField(upload_to='images/', null=True, blank=True)
    photo2 = models.ImageField(upload_to='images/', null=True, blank=True)
    rating = models.IntegerField(default=0)
    thermomix = models.BooleanField(default=False, blank=True)

    def dateformat(self):
        return self.added.strftime('%e.%m.%Y')

    # string representation
    def __str__(self):
        return self.name

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("detail", kwargs={'pk': self.pk})


# class Comment(models.Model):
#     post = models.ForeignKey('blog.Dish', related_name='comments', on_delete=models.CASCADE)
#     author = models.CharField(max_length=200)
#     text = models.TextField()
#     created_date = models.DateTimeField(default=timezone.now)
#     approved_comment = models.BooleanField(default=False)
#
#     def approve(self):
#         self.approved_comment = True
#         self.save()
#
#     def __str__(self):
#         return self.text
#
#     # after posting a comment redirect to home page
#     def get_absolute_url(self):
#         return reverse('home')

accounts/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

blog/views.py
from .models import Dish
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils import timezone
from django.urls import reverse_lazy

from django.contrib.auth.forms import UserCreationForm


# Class Based Views
class HomePageView(ListView):
    model = Dish
    template_name = 'blog/home.html'
    paginate_by = 8
    ordering = ['-added']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class DetailDishView(DetailView):
    model = Dish
    template_name = 'blog/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CreateDishView(CreateView):
    template_name = 'blog/create_dish.html'
    fields = (
        'name', 'portions', 'ingredients', 'description', 'added', 'photo0', 'photo1', 'photo2', 'rating', 'thermomix')
    model = Dish


class UpdateDishView(UpdateView):
    template_name = 'blog/create_dish.html'
    fields = (
        'name', 'portions', 'ingredients', 'description', 'added', 'photo0', 'photo1', 'photo2', 'rating', 'thermomix')
    model = Dish


class DeleteDishView(DeleteView):
    model = Dish
    success_url = reverse_lazy('home')

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body text-center">
                    <form method="post">
                        {% csrf_token %}
                        {% include 'template-form.html' %}
                        <button type="submit" class="btn btn-primary">Sign up</button>
                    </form>
                    {% endblock %}
                </div>
            </div>

        </div>
        <div class="col-sm-3"></div>
    </div>
</div>

blog/templates/blog/create_dish.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">

            <!--enctype ogarnie pliki-->
            <!--novalidate prevents the browser from "validating" the data before submitting to the server-->
            <form method="POST" enctype="multipart/form-data" novalidate>
                {% csrf_token %}

                <div class="form-group">
                    <!--DRY solution for templates form :) -->
                    {% include 'template-form.html' %}
                    <button type="submit" class="btn btn-primary btn-lg btn-block">Save</button>
                </div>
            </form>

        </div>
        <div class="col-sm-2"></div>
    </div>
</div>





{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="album bg-light">
    <div class="container">

        <div class="row">
            <div class="col-sm-10 text-center pb-4">
                <h2 class="dish_name">{{ dish.name }}</h2>
                <!-- <p class="font-weight-light">{{ dish.dateformat }}</p>  -->
            </div>
            <div class="col-sm-2 text-center pb-4">
                <!-- Delete -->
                {% if request.user.is_active and request.user.is_staff %}
                <form action="{% url 'dish-delete' dish.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="name" value="{{ dish.id }}">
                    <button type="submit" class="btn btn-light" data-toggle="tooltip" data-placement="top" title="Usuń">
                        <i class="material-icons md-48">delete_forever</i>
                    </button>
                </form>
                <!-- Update -->
                <form action="{% url 'dish-update' dish.id %}" method="get" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="name" value="{{ dish.id }}">
                    <button type="submit" class="btn btn-light" data-toggle="tooltip" data-placement="top" title="Edytuj">
                        <i class="material-icons md-48">edit</i>
                    </button>
                </form>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6"><img src="{{ dish.photo0.url }}" class="img-fluid rounded"></div>
            <div class="col-sm-6">
                <h5>Składniki:</h5>
                <p class="font-italic">{{ dish.portions }} porcje </p>
                <p>{{ dish.ingredients|linebreaks }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 pt-3">
                <h5>Przepis:</h5>
                <p>{{ dish.description|linebreaks }}</p>
            </div>
        </div>

    </div>
</div>

{% endblock %}

blog/templates/blog/home.html
{% extends 'base.html' %}
{% block content %}
<style>
    a.card,
    a.card:hover {
    color: pink;
    text-decoration: none;
    }
</style>

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">

                {% for danie in object_list %}

                <div class="col-lg-3 col-sm-6 text-center">
                    <a href="{% url 'detail' danie.id %}" class="card-columns">
                        <div class="card">
                            <div class="card-body text-center">
                                <h6 class="card-text" style="color:Black;">{{ danie.name }}</h6>
                                <!--          <p class="card-text"><small class="text-muted">{{ danie.dateformat }}</small></p> -->
                            </div>
                            <img class="card-img-bottom img-fluid rounded-bottom" src="{{ danie.photo0.url }}">
                        </div>
                    </a>
                </div>

                {% endfor %}

            </div>
        </div>

            {% if is_paginated %}
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span>
                    </a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span>
                    </a>
                </li>
                {% endif %}

                {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
                </li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                    </a>
                </li>
                {% else %}
                <li class="page-item"><a class="page-link" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %}

    </div>

{% endblock %}

widelcem/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Andre356">

    <title>Widelcem po łapie</title>
    {% load static %}

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ubuntu|Raleway" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
</head>

<body>
<header>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark pinky">
        <div class="container">
            <a class="navbar-brand mb-0 h1" href="{% url 'home' %}">Widelcem po łapie</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown1" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Rodzaj dania
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Dania główne</a>
                            <a class="dropdown-item" href="#">Zupy</a>
                            <a class="dropdown-item" href="#">Przystawki</a>
                            <a class="dropdown-item" href="#">Grill</a>
                            <a class="dropdown-item" href="#">Sałatki</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown2" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Okazja
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Wystawne</a>
                            <a class="dropdown-item" href="#">Na imprezę</a>
                            <a class="dropdown-item" href="#">Boże Narodzenie</a>
                            <a class="dropdown-item" href="#">Wielkanoc</a>
                            <a class="dropdown-item" href="#">Grill</a>
                            <a class="dropdown-item" href="#">Na żagle</a>
                            <a class="dropdown-item" href="#">Wałówka</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown3" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Produkt
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Kurczak</a>
                            <a class="dropdown-item" href="#">Wieprzowina</a>
                            <a class="dropdown-item" href="#">Wołowina</a>
                            <a class="dropdown-item" href="#">Krewetki</a>
                        </div>
                    </li>
                </ul>
                <!--<form class="form-inline my-2 my-lg-0">-->
                <!--<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
                <!--<button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>-->
                <!--</form>-->
                <ul class="navbar-nav ml-auto">
                    <li class="navbar-item">
                        {% if request.user.is_active and request.user.is_staff %}
                        <a class="nav-link active" href="{% url 'dish-create' %}">Dodaj danie</a>
                        {% endif %}
                    </li>
                    {% if user.is_authenticated %}
                    {% else %}
                    <li>
                        <a class="nav-link active" href="{% url 'accounts:signup' %}">Dołącz</a>
                    </li>
                    {% endif %}
                    <li class="navbar-item">
                        {% if user.is_authenticated %}
                        <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
                        {% else %}
                        <a class="nav-link active" href="{% url 'login' %}">Login</a>
                        {% endif %}
                    </li>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<main role="main" class="bg-light">

    <div class="container mt-5 pt-2 pb-0">
        <img src="{% static 'logo.png' %}" class="img-fluid mx-auto d-block" aria-hidden="true"/>
        <hr/>
    </div>


    {% block content %}
    {% endblock %}

</main>

<div class="album py-2 bg-light">
    <footer class="text-muted">
        <div class="container">
            <hr/>
            <p class="float-right">
                <a href="{% url 'home' %}">Back to top</a>
            </p>
            <p class="text-center">© {% now "Y" %}</p>
        </div>
    </footer>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();
});
</script>
</body>
</html>

widelcem/templates/template-form.html
{% load widget_tweaks %}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text|safe }}</small>
      {% endif %}
    </div>
  {% endfor %}